Feat: api내부 admin모듈 추가
boaz-lol/lp-server pull request #14
Opened 2024-04-18 11:24 UTC by oo-ni

2024-04-18 11:26 UTC, sunnyineverywhere requested changes
변경 후 언급 부탁드립니다!

2024-04-18 11:26 UTC, sunnyineverywhere commented on api/admin/src/main/resources/application.properties
application.properties 혹은 .yaml 파일은 .gitignore에 추가해주세요

2024-04-18 11:26 UTC, sunnyineverywhere commented on api/admin/src/main/kotlin/boaz/lol/co/AdminApplication.kt
이거 지워야합니다

2024-04-18 11:26 UTC, sunnyineverywhere commented on api/admin/build.gradle.kts
프로젝트 루트에 있는 plugin, group, version, java, repository 등과 겹쳐요
dependencies에는 security module 이외에는 불필요 할 것 같습니다

2024-04-19 07:05 UTC, oo-ni commented on api/admin/build.gradle.kts
이거 잘 이해가 안되긴한데 다시 확인 가능한가요

2024-04-19 17:09 UTC, sunnyineverywhere requested changes
admin 모듈 내부에도 build.gradle.kts 파일을 생성하시고, sprint security 및 authorization/authentication 관련 코드는 그 모듈에 따로 격리하는 것이 필요해 보입니다.
어렵다면 storage 모듈을 참고해보셔도 좋을 것 같아요

2024-04-19 17:09 UTC, sunnyineverywhere commented on api/admin/src/main/resources/application.yaml
이 파일 git tracking 지워주셔야 합니다! 아래 글 참고하면 좋을듯
[rm git tracking](https://seulcode.tistory.com/314)

2024-04-19 17:09 UTC, sunnyineverywhere commented on api/build.gradle.kts
>  }
admin 모듈 내부에 build.gradle.kts를 생성하고 `spring-security-web`을 `/api/admin/build.gradle.kts` 파일에만 추가해주시는 게 좋을 것 같습니다

2024-04-20 06:26 UTC, merged